version: '3.8'
services:

  pagina_paul_santana_react:
    build: .
    container_name: pagina_paul_santana_react
    volumes:
      - .:/app
    ports:
      - "80:3000"
    networks:
      - internal_network
  
networks:
  internal_network:
    driver: bridge